# fly.toml app configuration file generated for iavian-uptime-check-rust on 2025-12-02T15:05:16+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'iavian-uptime-check-rust'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 20

  [http_service.http_options]
    idle_timeout = 600

[checks]
  [checks.is_up]
    port = 8080
    type = 'http'
    interval = '1m0s'
    timeout = '10s'
    grace_period = '1m0s'
    method = 'get'
    path = '/ok'

[[vm]]
  size = 'shared-cpu-1x'
